# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        medium_thumb:
            filters:
                thumbnail: { size: [1200, 900], mode: outbound }
        small_thumb:
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
